[2023-01-17T22:55:23.059+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.transform_encoding_load_task manual__2023-01-17T22:48:12.753375+00:00 [queued]>
[2023-01-17T22:55:23.092+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.transform_encoding_load_task manual__2023-01-17T22:48:12.753375+00:00 [queued]>
[2023-01-17T22:55:23.093+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:55:23.094+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T22:55:23.094+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:55:23.127+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_encoding_load_task> on 2023-01-17 22:48:12.753375+00:00
[2023-01-17T22:55:23.142+0000] {standard_task_runner.py:55} INFO - Started process 10191 to run task
[2023-01-17T22:55:23.149+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'transform_encoding_load_task', 'manual__2023-01-17T22:48:12.753375+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpysj2bgof']
[2023-01-17T22:55:23.154+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask transform_encoding_load_task
[2023-01-17T22:55:23.314+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.transform_encoding_load_task manual__2023-01-17T22:48:12.753375+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T22:55:23.555+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=transform_encoding_load_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T22:48:12.753375+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T22:48:12.753375+00:00
[2023-01-17T22:55:23.570+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 110, in transform_encode_load
    df = pd.read_csv(filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/accidents_cleaned.csv'
[2023-01-17T22:55:23.629+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_data_etl_pipeline, task_id=transform_encoding_load_task, execution_date=20230117T224812, start_date=20230117T225523, end_date=20230117T225523
[2023-01-17T22:55:23.737+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task transform_encoding_load_task ([Errno 2] No such file or directory: '/opt/airflow/data/accidents_cleaned.csv'; 10191)
[2023-01-17T22:55:23.813+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T22:55:24.020+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
