[2023-01-17T22:36:02.237+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T22:35:54.538730+00:00 [queued]>
[2023-01-17T22:36:02.260+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T22:35:54.538730+00:00 [queued]>
[2023-01-17T22:36:02.262+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:36:02.263+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T22:36:02.265+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T22:36:02.306+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_integrate_dataset> on 2023-01-17 22:35:54.538730+00:00
[2023-01-17T22:36:02.327+0000] {standard_task_runner.py:55} INFO - Started process 9153 to run task
[2023-01-17T22:36:02.334+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'extract_integrate_dataset', 'manual__2023-01-17T22:35:54.538730+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpvn6ee_hw']
[2023-01-17T22:36:02.338+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask extract_integrate_dataset
[2023-01-17T22:36:02.460+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T22:35:54.538730+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T22:36:02.607+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_integrate_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T22:35:54.538730+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T22:35:54.538730+00:00
[2023-01-17T22:36:02.616+0000] {logging_mixin.py:137} INFO - got file paths successfully
[2023-01-17T22:36:06.251+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T22:36:29.649+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T22:36:35.409+0000] {logging_mixin.py:137} INFO - loaded CSVs files to df successfully
[2023-01-17T22:36:35.463+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 48, in extract_integrate
    suffixes=(None, '_DROP')).filter(regex='^(?!.*_DROP)')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9203, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 699, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1096, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'accident_reference'
[2023-01-17T22:36:35.682+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_data_etl_pipeline, task_id=extract_integrate_dataset, execution_date=20230117T223554, start_date=20230117T223602, end_date=20230117T223635
[2023-01-17T22:36:35.819+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task extract_integrate_dataset ('accident_reference'; 9153)
[2023-01-17T22:36:35.944+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T22:36:36.071+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
