[2023-01-17T21:29:41.230+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T21:28:53.105668+00:00 [queued]>
[2023-01-17T21:29:41.263+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T21:28:53.105668+00:00 [queued]>
[2023-01-17T21:29:41.264+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T21:29:41.287+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T21:29:41.288+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T21:29:41.357+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): cleanning_dataset> on 2023-01-17 21:28:53.105668+00:00
[2023-01-17T21:29:41.376+0000] {standard_task_runner.py:55} INFO - Started process 5711 to run task
[2023-01-17T21:29:41.382+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'cleanning_dataset', 'manual__2023-01-17T21:28:53.105668+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp1ifijww5']
[2023-01-17T21:29:41.386+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask cleanning_dataset
[2023-01-17T21:29:41.573+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.cleanning_dataset manual__2023-01-17T21:28:53.105668+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T21:29:42.409+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=cleanning_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T21:28:53.105668+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T21:28:53.105668+00:00
[2023-01-17T21:29:50.773+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T21:30:18.621+0000] {logging_mixin.py:137} INFO - Data Cleaned Successfully
[2023-01-17T21:30:18.647+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-17T21:30:18.670+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_data_etl_pipeline, task_id=cleanning_dataset, execution_date=20230117T212853, start_date=20230117T212941, end_date=20230117T213018
[2023-01-17T21:30:18.744+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-17T21:30:18.775+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
