[2023-01-17T21:03:25.489+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:56:58.079599+00:00 [queued]>
[2023-01-17T21:03:25.516+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:56:58.079599+00:00 [queued]>
[2023-01-17T21:03:25.517+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T21:03:25.518+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-17T21:03:25.519+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T21:03:25.548+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_integrate_dataset> on 2023-01-17 20:56:58.079599+00:00
[2023-01-17T21:03:25.558+0000] {standard_task_runner.py:55} INFO - Started process 4186 to run task
[2023-01-17T21:03:25.565+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'extract_integrate_dataset', 'manual__2023-01-17T20:56:58.079599+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpdln3qv1p']
[2023-01-17T21:03:25.568+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask extract_integrate_dataset
[2023-01-17T21:03:25.683+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:56:58.079599+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T21:03:26.460+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_integrate_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T20:56:58.079599+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T20:56:58.079599+00:00
[2023-01-17T21:03:26.517+0000] {logging_mixin.py:137} INFO - got file paths successfully
[2023-01-17T21:03:30.244+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T21:03:50.957+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T21:03:54.537+0000] {logging_mixin.py:137} INFO - loaded CSVs files to df successfully
[2023-01-17T21:03:54.542+0000] {logging_mixin.py:137} INFO - Index(['accident_year', 'location_easting_osgr', 'location_northing_osgr',
       'police_force', 'accident_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'first_road_class', 'road_type',
       'speed_limit', 'junction_detail', 'junction_control',
       'second_road_class', 'pedestrian_crossing_human_control',
       'pedestrian_crossing_physical_facilities', 'light_conditions',
       'weather_conditions', 'road_surface_conditions',
       'special_conditions_at_site', 'carriageway_hazards',
       'lsoa_of_accident_location', 'day_hour', 'vehicle_reference',
       'vehicle_type', 'towing_and_articulation', 'vehicle_manoeuvre',
       'vehicle_direction_from', 'vehicle_direction_to',
       'vehicle_location_restricted_lane', 'junction_location',
       'skidding_and_overturning', 'hit_object_in_carriageway',
       'vehicle_leaving_carriageway', 'hit_object_off_carriageway',
       'first_point_of_impact', 'vehicle_left_hand_drive',
       'journey_purpose_of_driver', 'sex_of_driver', 'age_of_driver',
       'age_band_of_driver', 'engine_capacity_cc', 'propulsion_code',
       'age_of_vehicle', 'generic_make_model', 'driver_imd_decile',
       'driver_home_area_type', 'lsoa_of_driver'],
      dtype='object')
[2023-01-17T21:03:54.549+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 48, in extract_integrate
    suffixes=(None, '_DROP')).filter(regex='^(?!.*_DROP)')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9203, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 699, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1096, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'accident_reference'
[2023-01-17T21:03:54.598+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=accidents_data_etl_pipeline, task_id=extract_integrate_dataset, execution_date=20230117T205658, start_date=20230117T210325, end_date=20230117T210354
[2023-01-17T21:03:54.629+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 31 for task extract_integrate_dataset ('accident_reference'; 4186)
[2023-01-17T21:03:54.677+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T21:03:54.730+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
