[2023-01-17T21:11:12.406+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T21:05:35.447783+00:00 [queued]>
[2023-01-17T21:11:12.432+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T21:05:35.447783+00:00 [queued]>
[2023-01-17T21:11:12.433+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T21:11:12.433+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-17T21:11:12.434+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T21:11:12.468+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_integrate_dataset> on 2023-01-17 21:05:35.447783+00:00
[2023-01-17T21:11:12.478+0000] {standard_task_runner.py:55} INFO - Started process 4597 to run task
[2023-01-17T21:11:12.488+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'extract_integrate_dataset', 'manual__2023-01-17T21:05:35.447783+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpqeloped1']
[2023-01-17T21:11:12.493+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask extract_integrate_dataset
[2023-01-17T21:11:12.633+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T21:05:35.447783+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T21:11:13.500+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_integrate_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T21:05:35.447783+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T21:05:35.447783+00:00
[2023-01-17T21:11:13.507+0000] {logging_mixin.py:137} INFO - got file paths successfully
[2023-01-17T21:11:16.719+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T21:11:47.162+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T21:11:53.410+0000] {logging_mixin.py:137} INFO - loaded CSVs files to df successfully
[2023-01-17T21:11:53.428+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 47, in extract_integrate
    suffixes=(None, '_DROP')).filter(regex='^(?!.*_DROP)')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9203, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 699, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1096, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'accident_reference'
[2023-01-17T21:11:53.553+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=accidents_data_etl_pipeline, task_id=extract_integrate_dataset, execution_date=20230117T210535, start_date=20230117T211112, end_date=20230117T211153
[2023-01-17T21:11:53.670+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task extract_integrate_dataset ('accident_reference'; 4597)
[2023-01-17T21:11:53.749+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T21:11:53.941+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
