[2023-01-17T20:54:00.001+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:53:55.251089+00:00 [queued]>
[2023-01-17T20:54:00.030+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:53:55.251089+00:00 [queued]>
[2023-01-17T20:54:00.031+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T20:54:00.036+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T20:54:00.042+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T20:54:00.102+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_integrate_dataset> on 2023-01-17 20:53:55.251089+00:00
[2023-01-17T20:54:00.140+0000] {standard_task_runner.py:55} INFO - Started process 3691 to run task
[2023-01-17T20:54:00.153+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_data_etl_pipeline', 'extract_integrate_dataset', 'manual__2023-01-17T20:53:55.251089+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpqo0pqkv8']
[2023-01-17T20:54:00.158+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask extract_integrate_dataset
[2023-01-17T20:54:00.517+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_data_etl_pipeline.extract_integrate_dataset manual__2023-01-17T20:53:55.251089+00:00 [running]> on host 7fc7752d3cb4
[2023-01-17T20:54:01.695+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_data_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_integrate_dataset
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T20:53:55.251089+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T20:53:55.251089+00:00
[2023-01-17T20:54:01.745+0000] {logging_mixin.py:137} INFO - got file paths successfully
[2023-01-17T20:54:11.105+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T20:54:39.773+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (10,28,29) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-17T20:55:08.713+0000] {logging_mixin.py:137} INFO - loaded CSVs files to df successfully
[2023-01-17T20:55:08.764+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 40, in extract_integrate
    prnt(dfs[i].dtypes)
NameError: name 'prnt' is not defined
[2023-01-17T20:55:09.696+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=accidents_data_etl_pipeline, task_id=extract_integrate_dataset, execution_date=20230117T205355, start_date=20230117T205400, end_date=20230117T205509
[2023-01-17T20:55:10.053+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task extract_integrate_dataset (name 'prnt' is not defined; 3691)
[2023-01-17T20:55:10.327+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T20:55:11.719+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
